# Generated by Django 5.2.6 on 2025-09-23 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb_auth', '0001_initial'),
        ('fb_post', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='FbUser',
        ),
    ]
