# Generated by Django 5.2.6 on 2025-09-23 05:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fb_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('posted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fb_post.group')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb_auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('commented_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb_auth.user')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fb_post.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb_post.post')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb_post.group')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb_auth.user')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('group', 'member'), name='unique_group_members')],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('WOW', 'wow'), ('LIT', 'lit'), ('LOVE', 'Love'), ('HAHA', 'Haha'), ('THUMBS-UP', 'Thumbs-up'), ('THUMPS-DOWN', 'Thumps-down'), ('ANGRY', 'Angry'), ('SAD', 'Sad')], max_length=30)),
                ('reacted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fb_post.comment')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fb_post.post')),
                ('reacted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb_auth.user')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('reacted_by', 'post'), name='unique_user_post_reaction'), models.UniqueConstraint(fields=('reacted_by', 'comment'), name='unique_user_comment_reaction')],
            },
        ),
    ]
